name: Auto Check Solution

on:
  pull_request:
    branches: [main]

jobs:
  create-pull-requst:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Setup Python Package
        run: |
          python -m pip install --upgrade pip
          pip install bs4 requests
      - name: Check Solution
        run: |
          python scripts/check_pull_reqeust.py --pr_number ${{ github.event.number }}
